# Travis-CI Build for BooJs
# see travis-ci.org for details

language: c

# Make sure mono is installed
install:
 - echo "Installing Mono..."
  # Make sure mono is installed,
  # pipe stdout to dev/null because qq is still too chatty
  - sudo apt-get update -qq #> /dev/null
  # mono-utils: pedump
  - sudo apt-get install -qq mono-devel mono-utils #> /dev/null
  - sudo apt-get install -qq nant #> /dev/null
  - sudo apt-get install -qq nunit-console #> /dev/null
  # Make sure root certificates are in place
  - mozroots --import --sync

# Run the Build script
script:
 - nant rebuild
 - mono --runtime=v4.0 /usr/lib/nunit/nunit-console.exe tests/build/*Tests.dll

# Notify development list when needed
notifications:
 recipients:
   - drslump@pollinimini.net
 email:
   on_success: change
   on_failure: always
